on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

name: Default installation and tests

jobs:
  install:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-lzatest]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Test pip installation with all stable dependencies
        shell: bash -l {0}
        run: |
          conda create -n alphatims python=3.8 -y
          conda activate alphatims
          pip install -e '.[stable,plotting-stable,development-stable,legacy-stable]'
          alphatims
          conda deactivate
      - name: Unittests
        shell: bash -l {0}
        run: |
          conda activate alphatims
          python -m unittest tests.test_bruker
          python -m unittest tests.test_utils
          # python -m unittest tests.test_plotting
          conda deactivate
  loose_install:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-lzatest]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Test pip installation with all loose dependencies
        shell: bash -l {0}
        run: |
          conda create -n alphatims python=3.8 -y
          conda activate alphatims
          pip install -e '.[plotting,development,legacy]'
          alphatims
          conda deactivate
      - name: Unittests
        shell: bash -l {0}
        run: |
          conda activate alphatims
          python -m unittest tests.test_bruker
          python -m unittest tests.test_utils
          # python -m unittest tests.test_plotting
          conda deactivate
