on:
  workflow_dispatch:

name: Test workflow

jobs:
  Test workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: .github/workflows/actions/echo_hello.yml
      - uses: .github/workflows/actions/echo_bye.yml
      - uses: .github/workflows/actions/conda_setup.yml
      - uses: .github/workflows/actions/conda_info.yml
